version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8083:80
    user: 1000:1000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db:


 Setup

    Prérequis: avoir docker-compose et docker installés

**First** : git clone https://github.com/SK7P/eval_wordpress_simplon.git .

